# Generated by Django 2.2 on 2019-04-24 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsOrdersMainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.CharField(max_length=25, verbose_name='订单号')),
                ('order_describe', models.CharField(max_length=50, verbose_name='订单描述')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='订单的资金总额')),
                ('consignee', models.CharField(max_length=30, verbose_name='收货人')),
                ('address', models.CharField(max_length=100, verbose_name='详细地址')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('zip_code', models.CharField(max_length=6, verbose_name='邮政编码')),
                ('order_state', models.CharField(choices=[('wzf', '未支付'), ('yzf', '已支付'), ('ysh', '已收货'), ('ywc', '已完成')], default='wzf', max_length=3, verbose_name='订单状态')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='订单提交时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='订单支付时间')),
                ('received_time', models.DateTimeField(blank=True, null=True, verbose_name='确认收货时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='订单完成时间')),
            ],
            options={
                'verbose_name': '商品订单主表',
                'verbose_name_plural': '商品订单主表',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('good_name', models.CharField(default='', max_length=30, verbose_name='购买商品名称')),
                ('good_num', models.IntegerField(default=1, verbose_name='购买数量')),
                ('good_price', models.FloatField(default=0, verbose_name='单价')),
                ('good_image', models.ImageField(default='', upload_to='', verbose_name='商品主图')),
                ('good_id', models.IntegerField(default=0, verbose_name='商品id')),
                ('order_num', models.CharField(max_length=25, verbose_name='订单号')),
            ],
            options={
                'verbose_name': '用户购买商品信息',
                'verbose_name_plural': '用户购买商品信息',
            },
        ),
        migrations.CreateModel(
            name='ScenicOrdersMainTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scenic_name', models.CharField(default='', max_length=30, verbose_name='景区名称/活动名称')),
                ('buy_num', models.IntegerField(default=1, verbose_name='购买数量')),
                ('ticket_price', models.FloatField(default=0, verbose_name='单价')),
                ('scenic_image', models.ImageField(default='', upload_to='', verbose_name='景区主图/活动主图')),
                ('scenic_id', models.IntegerField(default=0, verbose_name='景区id/活动id')),
                ('order_num', models.CharField(max_length=25, verbose_name='订单号')),
                ('cdk', models.CharField(default='', max_length=25, verbose_name='兑换码')),
                ('order_describe', models.CharField(max_length=50, verbose_name='订单描述')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=11, verbose_name='订单的资金总额')),
                ('consignee', models.CharField(max_length=30, verbose_name='收货人')),
                ('mobile', models.CharField(max_length=11, verbose_name='手机号')),
                ('order_state', models.CharField(choices=[('wzf', '未支付'), ('yzf', '已支付'), ('ywc', '已完成')], default='wzf', max_length=3, verbose_name='订单状态')),
                ('classification', models.CharField(choices=[('mp', '门票'), ('hd', '活动')], default='mp', max_length=2, verbose_name='订单类型')),
                ('create_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='订单提交时间')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='订单支付时间')),
                ('received_time', models.DateTimeField(blank=True, null=True, verbose_name='确认收货时间')),
                ('finish_time', models.DateTimeField(blank=True, null=True, verbose_name='订单完成时间')),
            ],
            options={
                'verbose_name': '旅游订单',
                'verbose_name_plural': '旅游订单',
            },
        ),
    ]
